"""
CVD Risk Prediction Web App
----------------------------
Loads the model + scaler + feature list saved from cvd_analysis.ipynb
and serves a simple form for doctors to enter the 5 key clinical features,
returning a risk % and a SHAP-based explanation.

Run:
    pip install flask joblib shap matplotlib numpy pandas
    python app.py
Then open http://127.0.0.1:5000 in your browser.

IMPORTANT: This file must sit in the SAME folder as:
    cvd_model.pkl, scaler.pkl, top5_features.pkl, threshold.pkl
(these are generated by running cvd_analysis.ipynb)
"""

import io
import base64

import joblib
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")  # no GUI needed, we render to PNG bytes
import matplotlib.pyplot as plt
import shap

import uuid
import bcrypt
from datetime import datetime
from flask import Flask, render_template_string, request, jsonify, redirect, url_for, send_file
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required, current_user

# ReportLab imports for PDF generation
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors


app = Flask(__name__)
app.config['SECRET_KEY'] = 'cvd_secure_secret_key_12345'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///cvd_database.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)

login_manager = LoginManager()
login_manager.login_view = 'login'
login_manager.init_app(app)


# ---------- Database Models ----------
class Patient(db.Model):
    __tablename__ = 'patients'
    
    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    name = db.Column(db.String(100), nullable=False)
    gender = db.Column(db.String(10), nullable=False)  # "Male" or "Female"
    dob = db.Column(db.String(10), nullable=False)     # YYYY-MM-DD
    fhir_id = db.Column(db.String(50), nullable=True, unique=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # Relationship to visits
    visits = db.relationship('Visit', backref='patient', lazy=True, cascade="all, delete-orphan")


class Visit(db.Model):
    __tablename__ = 'visits'
    
    id = db.Column(db.Integer, primary_key=True)
    patient_id = db.Column(db.String(36), db.ForeignKey('patients.id'), nullable=False)
    visit_date = db.Column(db.DateTime, default=datetime.utcnow)
    
    # Clinical metrics
    sex = db.Column(db.String(10), nullable=False)
    exercise_angina = db.Column(db.String(10), nullable=False)
    st_slope = db.Column(db.String(10), nullable=False)
    chest_pain = db.Column(db.String(10), nullable=False)
    oldpeak = db.Column(db.Float, nullable=False)
    
    # Risk prediction
    predicted_risk = db.Column(db.Float, nullable=False)
    is_high_risk = db.Column(db.Boolean, nullable=False)


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)
    role = db.Column(db.String(20), nullable=False, default="Clinician")  # "Clinician" or "Administrator"

    def set_password(self, password):
        self.password_hash = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

    def check_password(self, password):
        return bcrypt.checkpw(password.encode('utf-8'), self.password_hash.encode('utf-8'))


class AuditLog(db.Model):
    __tablename__ = 'audit_logs'
    
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)
    username = db.Column(db.String(50), nullable=True)
    action = db.Column(db.String(100), nullable=False)
    patient_id = db.Column(db.String(36), nullable=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    ip_address = db.Column(db.String(45), nullable=True)
    
    # Relationship to user
    user = db.relationship('User', backref=db.backref('audit_logs', lazy=True))


@login_manager.user_loader
def load_user(user_id):
    return db.session.get(User, int(user_id))


@app.route("/static/login_art.jpg")
def serve_login_art():
    return send_file(r"C:\Users\DELL\.gemini\antigravity\brain\2a11a59f-b1f9-4f46-8674-9a51da9ee8ea\cvd_login_art_1785351878332.jpg")


def log_audit(action, patient_id=None):
    """Utility to log user actions for compliance auditing."""
    user_id = current_user.id if current_user.is_authenticated else None
    username = current_user.username if current_user.is_authenticated else "Anonymous"
    ip = request.remote_addr
    log_entry = AuditLog(
        user_id=user_id,
        username=username,
        action=action,
        patient_id=patient_id,
        ip_address=ip
    )
    db.session.add(log_entry)
    db.session.commit()


# Create tables and seed default users on startup
with app.app_context():
    db.create_all()
    
    # Dynamically upgrade schema for patients table if fhir_id is missing
    from sqlalchemy import text
    try:
        db.session.execute(text("ALTER TABLE patients ADD COLUMN fhir_id VARCHAR(50)"))
        db.session.commit()
        print("Database migrated: fhir_id column added to patients table.")
    except Exception:
        db.session.rollback()

    if User.query.first() is None:
        # Seed admin
        admin = User(username="admin", role="Administrator")
        admin.set_password("admin123")
        db.session.add(admin)
        
        # Seed clinician
        doctor = User(username="doctor", role="Clinician")
        doctor.set_password("doctor123")
        db.session.add(doctor)
        db.session.commit()
        print("Default users seeded (admin/admin123, doctor/doctor123).")



# ---------- Load saved artifacts ----------
model = joblib.load("cvd_model.pkl")
scaler = joblib.load("scaler.pkl")
top5_features = joblib.load("top5_features.pkl")
threshold = joblib.load("threshold.pkl")

# Map from scaler's fitted feature order -> index, so we can pull the
# correct mean/scale for each of our 5 features even though the scaler
# was originally fit on all 15 columns.
scaler_feature_order = list(scaler.feature_names_in_)

explainer = shap.TreeExplainer(model)


CHEST_PAIN_EDUCATION = {
    "TA": {
        "name": "Typical Angina",
        "description": "Chest pain or pressure that happens when the heart muscle does not get enough oxygen-rich blood. This is usually triggered by physical activity, heavy meals, or emotional stress, and typically subsides with rest or nitroglycerin.",
        "causes": "Narrowing or blockages in the coronary arteries that supply blood to the heart (Coronary Artery Disease).",
        "overcome": "Follow a cardiologist-supervised care plan. This often includes heart-healthy dietary changes (low-fat, low-sodium), regular moderate exercise as tolerated, taking prescribed medications (such as beta-blockers or antiplatelet agents), and avoiding sudden overexertion."
    },
    "ATA": {
        "name": "Atypical Angina",
        "description": "Chest discomfort that does not fit the typical description. It may present as shortness of breath, indigestion, fatigue, or radiating pain in the back, neck, or jaw. It is particularly common in women, older adults, and individuals with diabetes.",
        "causes": "Spasms in the heart's blood vessels or dysfunction in the very small coronary arteries (Microvascular Disease).",
        "overcome": "Keep a daily symptom diary to track triggers, manage stress through breathing exercises, limit caffeine, take prescribed calcium-channel blockers or other treatments, and monitor for changes in pain patterns."
    },
    "NAP": {
        "name": "Non-Anginal Pain",
        "description": "Chest discomfort that is unlikely to be related to a heart condition. This pain often changes when you take a deep breath, press on your chest wall, or shift your physical posture.",
        "causes": "Common non-cardiac causes include gastroesophageal reflux (acid reflux/heartburn), muscle strain or joint inflammation in the chest wall (costochondritis), or panic/anxiety attacks.",
        "overcome": "Treat the underlying non-cardiac cause. For reflux, avoid lying down immediately after eating and eat smaller meals. For muscle pain, use warm compresses and rest. For anxiety-related pain, practice mindfulness and consult a therapist if needed."
    },
    "ASY": {
        "name": "Asymptomatic",
        "description": "No chest pain, pressure, or discomfort is felt. Even without symptoms, cardiovascular risk can still be elevated due to other underlying silent indicators.",
        "causes": "Silent myocardial ischemia, which is often seen in individuals with diabetes because nerve damage (neuropathy) can block pain signals from the heart.",
        "overcome": "Ensure regular checkups with your doctor. Focus on strict control of blood pressure, blood sugar, and cholesterol, and follow a balanced diet and safe exercise regimen."
    }
}


# ---------- Figure out which raw form fields we need ----------
# top5_features will look something like:
# ['ST_Slope_Up', 'Sex_M', 'ExerciseAngina_Y', 'ChestPainType_ATA', 'ChestPainType_NAP']
# We build the form dynamically based on what's actually in top5_features,
# so this works even if your feature selection picked slightly different ones.

FIELD_DEFINITIONS = {
    "Sex_M": {
        "label": "Sex",
        "type": "select",
        "options": [("Male", 1), ("Female", 0)],
    },
    "ExerciseAngina_Y": {
        "label": "Exercise-induced Angina?",
        "type": "select",
        "options": [("Yes", 1), ("No", 0)],
    },
    "Oldpeak": {
        "label": "Oldpeak (ST depression value, e.g. 1.2)",
        "type": "number",
    },
    "ST_Slope_Flat": {"label": "ST Slope", "type": "st_slope"},
    "ST_Slope_Up": {"label": "ST Slope", "type": "st_slope"},
    "ChestPainType_ATA": {"label": "Chest Pain Type", "type": "chest_pain"},
    "ChestPainType_NAP": {"label": "Chest Pain Type", "type": "chest_pain"},
    "ChestPainType_TA": {"label": "Chest Pain Type", "type": "chest_pain"},
}

# de-duplicate grouped fields (ST slope / chest pain each produce multiple
# one-hot columns but should show as ONE dropdown in the form)
def build_form_fields(features):
    seen_groups = set()
    fields = []
    for f in features:
        definition = FIELD_DEFINITIONS.get(f)
        if definition is None:
            fields.append({"key": f, "label": f, "type": "number"})
            continue
        group = definition["type"]
        if group in ("st_slope", "chest_pain"):
            if group in seen_groups:
                continue
            seen_groups.add(group)
        field_data = {"key": f, "label": definition["label"], "type": definition["type"]}
        if "options" in definition:
            field_data["options"] = definition["options"]
        fields.append(field_data)
    return fields


FORM_FIELDS = build_form_fields(top5_features)


def encode_input(form_data):
    """Turn form input into the exact 5-column vector the model expects,
    scaled using the same per-column mean/std the scaler learned."""
    raw = {feat: 0.0 for feat in top5_features}

    st_slope_choice = form_data.get("ST_Slope")   # "Up", "Flat", "Down"
    chest_pain_choice = form_data.get("ChestPainType")  # "ATA","NAP","TA","ASY"

    for feat in top5_features:
        if feat == "Sex_M":
            raw[feat] = float(form_data.get("Sex_M", 0))
        elif feat == "ExerciseAngina_Y":
            raw[feat] = float(form_data.get("ExerciseAngina_Y", 0))
        elif feat == "Oldpeak":
            raw[feat] = float(form_data.get("Oldpeak", 0))
        elif feat == "ST_Slope_Up":
            raw[feat] = 1.0 if st_slope_choice == "Up" else 0.0
        elif feat == "ST_Slope_Flat":
            raw[feat] = 1.0 if st_slope_choice == "Flat" else 0.0
        elif feat == "ChestPainType_ATA":
            raw[feat] = 1.0 if chest_pain_choice == "ATA" else 0.0
        elif feat == "ChestPainType_NAP":
            raw[feat] = 1.0 if chest_pain_choice == "NAP" else 0.0
        elif feat == "ChestPainType_TA":
            raw[feat] = 1.0 if chest_pain_choice == "TA" else 0.0

    # Scale each feature using its own mean/std from the fitted scaler
    scaled_values = []
    for feat in top5_features:
        idx = scaler_feature_order.index(feat)
        mean = scaler.mean_[idx]
        std = scaler.scale_[idx]
        scaled_values.append((raw[feat] - mean) / std)

    X = pd.DataFrame([scaled_values], columns=top5_features)
    return X


def make_shap_chart(X_row, shap_row, base_value):
    """Render a simple horizontal bar chart of SHAP contributions to a PNG (base64)."""
    # Group features by their form input representations (aligns 5 binary features to 4 form inputs)
    groups = {
        "Sex": [],
        "Exercise-induced Angina": [],
        "ST Slope": [],
        "Chest Pain Type": [],
        "Oldpeak (ST Depression)": []
    }
    
    for i, feat in enumerate(top5_features):
        val = shap_row[i]
        if feat.startswith("Sex"):
            groups["Sex"].append(val)
        elif feat.startswith("ExerciseAngina"):
            groups["Exercise-induced Angina"].append(val)
        elif feat.startswith("ST_Slope"):
            groups["ST Slope"].append(val)
        elif feat.startswith("ChestPainType"):
            groups["Chest Pain Type"].append(val)
        elif feat.startswith("Oldpeak"):
            groups["Oldpeak (ST Depression)"].append(val)
        else:
            clean_name = feat.replace("_", " ")
            if clean_name not in groups:
                groups[clean_name] = []
            groups[clean_name].append(val)
            
    # Sum the SHAP values in each group
    grouped_features = []
    grouped_shap = []
    for group_name, vals in groups.items():
        if len(vals) > 0:
            grouped_features.append(group_name)
            grouped_shap.append(sum(vals))
            
    grouped_features = np.array(grouped_features)
    grouped_shap = np.array(grouped_shap)
    
    # Create figure with clean transparent background
    fig, ax = plt.subplots(figsize=(6, 2.2), facecolor='none')
    ax.set_facecolor('none')
    
    # Custom dashboard colors (emerald for negative/reducing risk, crimson for positive/increasing risk)
    colors = ["#ef4444" if v > 0 else "#10b981" for v in grouped_shap]
    order = np.argsort(np.abs(grouped_shap))
    
    # Plot bars
    ax.barh(grouped_features[order], grouped_shap[order],
            color=np.array(colors)[order], height=0.55)
    
    # Add vertical line at zero
    ax.axvline(0, color='#cbd5e1', linestyle='-', linewidth=0.8)
    
    # Clean up axes & spines
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color('#cbd5e1')
    ax.spines['bottom'].set_color('#cbd5e1')
    
    ax.tick_params(colors='#475569', labelsize=9)
    ax.xaxis.label.set_color('#475569')
    ax.xaxis.label.set_size(9)
    ax.set_xlabel("Contribution to Risk (SHAP Value)")
    
    plt.tight_layout()

    buf = io.BytesIO()
    # Save figure with transparent facecolor to blend with card
    plt.savefig(buf, format="png", dpi=120, bbox_inches='tight', transparent=True)
    plt.close(fig)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("utf-8")


def make_trajectory_chart(visits):
    """Render a line chart of risk progression over time."""
    if len(visits) < 2:
        return None
    # Create figure with clean transparent background
    fig, ax = plt.subplots(figsize=(6, 2.2), facecolor='none')
    ax.set_facecolor('none')
    
    # Sort visits by date
    sorted_visits = sorted(visits, key=lambda v: v.visit_date)
    dates = [v.visit_date.strftime("%m/%d %H:%M") for v in sorted_visits]
    risks = [v.predicted_risk for v in sorted_visits]
    
    ax.plot(dates, risks, marker='o', color='#4f46e5', linewidth=2, markersize=6)
    ax.set_ylim(0, 100)
    
    # Styling
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color('#cbd5e1')
    ax.spines['bottom'].set_color('#cbd5e1')
    
    ax.tick_params(colors='#475569', labelsize=9)
    ax.xaxis.label.set_color('#475569')
    ax.yaxis.label.set_color('#475569')
    ax.set_ylabel("Risk %")
    ax.set_xlabel("Visit Date")
    
    plt.tight_layout()
    
    buf = io.BytesIO()
    plt.savefig(buf, format="png", dpi=120, bbox_inches='tight', transparent=True)
    plt.close(fig)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("utf-8")


def get_clinical_recommendations(risk_pct, form_data):
    """Generate clinical guidance based on prediction score and patient indicators."""
    recs = []
    
    # General risk recommendations
    if risk_pct >= 60:
        recs.append("High probability of coronary artery disease. Urgent referral to a cardiologist for clinical evaluation is recommended.")
    elif risk_pct >= 30:
        recs.append("Intermediate risk. Recommend a non-invasive Cardiac Stress Test (stress ECG) or coronary CT angiography (CCTA) to evaluate ischemia.")
    else:
        recs.append("Low risk based on selected indicators. Continue primary prevention, blood pressure control, lipid management, and routine wellness checkups.")
        
    # Attribute-specific indicators
    st_slope = form_data.get("ST_Slope", "Up")
    exercise_angina = form_data.get("ExerciseAngina_Y", "0")
    oldpeak = float(form_data.get("Oldpeak", 0))
    chest_pain = form_data.get("ChestPainType", "ATA")
    
    if st_slope in ["Flat", "Down"]:
        recs.append("Abnormal ST-segment slope (Flat/Down) detected on exercise ECG, which is highly indicative of myocardial ischemia.")
        
    if exercise_angina == "1":
        recs.append("Patient experienced angina during physical exertion, suggesting inducible myocardial ischemia under stress.")
        
    if oldpeak > 1.0:
        recs.append(f"ST depression of {oldpeak} mm is clinically significant. Depressions > 1.0 mm suggest moderate-to-severe coronary stenosis.")
        
    if chest_pain == "TA":
        recs.append("Typical substernal chest pain provoked by exertion suggests classical angina. Further evaluation is strongly advised.")
        
    return recs


LOGIN_TEMPLATE = """

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login - CVD CDSS</title>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg-color: #f1f5f9;
            --card-bg: #ffffff;
            --text-main: #0f172a;
            --text-muted: #64748b;
            --primary: #4f46e5;
            --primary-hover: #4338ca;
            --border-color: #e2e8f0;
            --error-color: #dc2626;
        }

        body {
            font-family: 'Outfit', sans-serif;
            background-color: var(--bg-color);
            color: var(--text-main);
            margin: 0;
            padding: 0;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .split-container {
            display: grid;
            grid-template-columns: 1fr 1fr;
            width: 100%;
            min-height: 100vh;
        }

        .image-panel {
            background-image: url('/static/login_art.jpg');
            background-size: cover;
            background-position: center;
            position: relative;
            display: flex;
            flex-direction: column;
            justify-content: flex-end;
            padding: 4rem;
            color: white;
        }

        .image-panel::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: linear-gradient(135deg, rgba(30, 27, 75, 0.4) 0%, rgba(15, 23, 42, 0.8) 100%);
            z-index: 1;
        }

        .image-overlay {
            position: relative;
            z-index: 2;
        }

        .overlay-text h2 {
            font-size: 2rem;
            font-weight: 700;
            margin-bottom: 0.5rem;
            text-shadow: 0 2px 4px rgba(0,0,0,0.3);
        }

        .overlay-text p {
            font-size: 1rem;
            color: #cbd5e1;
            max-width: 480px;
            line-height: 1.6;
            text-shadow: 0 1px 2px rgba(0,0,0,0.3);
        }

        .form-panel {
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 2.5rem;
            background-color: #f8fafc;
        }

        .login-card {
            background-color: var(--card-bg);
            border: 1px solid var(--border-color);
            border-radius: 0.75rem;
            box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.05), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
            width: 100%;
            max-width: 420px;
            padding: 2.5rem;
        }

        .login-header {
            text-align: center;
            margin-bottom: 2rem;
        }

        .login-header h1 {
            font-size: 1.75rem;
            font-weight: 700;
            margin: 0 0 0.5rem 0;
            color: var(--text-main);
            background: linear-gradient(135deg, #1e1b4b 0%, #4f46e5 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        .login-header p {
            color: var(--text-muted);
            margin: 0;
            font-size: 0.95rem;
        }

        .form-group {
            margin-bottom: 1.5rem;
        }

        .form-group label {
            display: block;
            font-size: 0.875rem;
            font-weight: 500;
            margin-bottom: 0.5rem;
            color: var(--text-main);
        }

        .form-group input {
            width: 100%;
            padding: 0.75rem 1rem;
            border: 1px solid var(--border-color);
            border-radius: 0.5rem;
            font-family: inherit;
            font-size: 0.95rem;
            color: var(--text-main);
            box-sizing: border-box;
            transition: all 0.2s ease;
        }

        .form-group input:focus {
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 3px rgba(79, 70, 229, 0.15);
        }

        .error-message {
            background-color: rgba(220, 38, 38, 0.1);
            color: var(--error-color);
            padding: 0.75rem 1rem;
            border-radius: 0.5rem;
            font-size: 0.9rem;
            margin-bottom: 1.5rem;
            text-align: center;
            border: 1px solid rgba(220, 38, 38, 0.2);
        }

        button {
            width: 100%;
            background-color: var(--primary);
            color: white;
            border: none;
            border-radius: 0.5rem;
            padding: 0.75rem;
            font-size: 1rem;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.2s ease;
            box-shadow: 0 2px 4px rgba(79, 70, 229, 0.2);
        }

        button:hover {
            background-color: var(--primary-hover);
            box-shadow: 0 4px 12px rgba(79, 70, 229, 0.25);
            transform: translateY(-1px);
        }

        button:active {
            transform: translateY(0);
        }

        @media (max-width: 850px) {
            .split-container {
                grid-template-columns: 1fr;
            }
            .image-panel {
                display: none;
            }
            .form-panel {
                padding: 1.5rem;
            }
        }
    </style>
</head>
<body>
    <div class="split-container">
        <!-- Left Side: Image Panel -->

        <div class="image-panel">
            <div class="image-overlay">
                <div class="overlay-text">
                    <h2>Advanced Cardiovascular Diagnostics</h2>
                    <p>Clinical Decision Support powered by explainable AI algorithms.</p>
                </div>
            </div>
        </div>
        
        <!-- Right Side: Form Panel -->
        <div class="form-panel">
            <div class="login-card">
                <div class="login-header">
                    <h1>CVD CDSS</h1>
                    <p>Clinical Decision Support Login</p>
                </div>
                
                {% if error %}
                    <div class="error-message">{{ error }}</div>
                {% endif %}
                
                <form method="POST">
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" name="username" id="username" required placeholder="doctor">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" name="password" id="password" required placeholder="••••••••">
                    </div>
                    <button type="submit">Log In</button>
                </form>
                
                <div style="margin-top: 1.5rem; text-align: center; font-size: 0.9rem; color: var(--text-muted);">
                    New medical staff? <a href="/register" style="color: var(--primary); font-weight: 600; text-decoration: none;">Register as Doctor</a>
                </div>
                
                <div style="margin-top: 2rem; text-align: center; font-size: 0.8rem; color: var(--text-muted);">
                    Secure Session • HIPAA Audited
                </div>
            </div>
        </div>
    </div>
</body>
</html>
"""


REGISTER_TEMPLATE = """

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register - CVD CDSS</title>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg-color: #f1f5f9;
            --card-bg: #ffffff;
            --text-main: #0f172a;
            --text-muted: #64748b;
            --primary: #4f46e5;
            --primary-hover: #4338ca;
            --border-color: #e2e8f0;
            --error-color: #dc2626;
            --success-color: #16a34a;
        }

        body {
            font-family: 'Outfit', sans-serif;
            background-color: var(--bg-color);
            color: var(--text-main);
            margin: 0;
            padding: 0;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .split-container {
            display: grid;
            grid-template-columns: 1fr 1fr;
            width: 100%;
            min-height: 100vh;
        }

        .image-panel {
            background-image: url('/static/login_art.jpg');
            background-size: cover;
            background-position: center;
            position: relative;
            display: flex;
            flex-direction: column;
            justify-content: flex-end;
            padding: 4rem;
            color: white;
        }

        .image-panel::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: linear-gradient(135deg, rgba(30, 27, 75, 0.4) 0%, rgba(15, 23, 42, 0.8) 100%);
            z-index: 1;
        }

        .image-overlay {
            position: relative;
            z-index: 2;
        }

        .overlay-text h2 {
            font-size: 2rem;
            font-weight: 700;
            margin-bottom: 0.5rem;
            text-shadow: 0 2px 4px rgba(0,0,0,0.3);
        }

        .overlay-text p {
            font-size: 1rem;
            color: #cbd5e1;
            max-width: 480px;
            line-height: 1.6;
            text-shadow: 0 1px 2px rgba(0,0,0,0.3);
        }

        .form-panel {
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 2.5rem;
            background-color: #f8fafc;
        }

        .login-card {
            background-color: var(--card-bg);
            border: 1px solid var(--border-color);
            border-radius: 0.75rem;
            box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.05), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
            width: 100%;
            max-width: 420px;
            padding: 2.5rem;
        }

        .login-header {
            text-align: center;
            margin-bottom: 2rem;
        }

        .login-header h1 {
            font-size: 1.75rem;
            font-weight: 700;
            margin: 0 0 0.5rem 0;
            color: var(--text-main);
            background: linear-gradient(135deg, #1e1b4b 0%, #4f46e5 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        .login-header p {
            color: var(--text-muted);
            margin: 0;
            font-size: 0.95rem;
        }

        .form-group {
            margin-bottom: 1.5rem;
        }

        .form-group label {
            display: block;
            font-size: 0.875rem;
            font-weight: 500;
            margin-bottom: 0.5rem;
            color: var(--text-main);
        }

        .form-group input {
            width: 100%;
            padding: 0.75rem 1rem;
            border: 1px solid var(--border-color);
            border-radius: 0.5rem;
            font-family: inherit;
            font-size: 0.95rem;
            color: var(--text-main);
            box-sizing: border-box;
            transition: all 0.2s ease;
        }

        .form-group input:focus {
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 3px rgba(79, 70, 229, 0.15);
        }

        .error-message {
            background-color: rgba(220, 38, 38, 0.1);
            color: var(--error-color);
            padding: 0.75rem 1rem;
            border-radius: 0.5rem;
            font-size: 0.9rem;
            margin-bottom: 1.5rem;
            text-align: center;
            border: 1px solid rgba(220, 38, 38, 0.2);
        }

        .success-message {
            background-color: rgba(22, 163, 74, 0.1);
            color: var(--success-color);
            padding: 0.75rem 1rem;
            border-radius: 0.5rem;
            font-size: 0.9rem;
            margin-bottom: 1.5rem;
            text-align: center;
            border: 1px solid rgba(22, 163, 74, 0.2);
        }

        button {
            width: 100%;
            background-color: var(--primary);
            color: white;
            border: none;
            border-radius: 0.5rem;
            padding: 0.75rem;
            font-size: 1rem;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.2s ease;
            box-shadow: 0 2px 4px rgba(79, 70, 229, 0.2);
        }

        button:hover {
            background-color: var(--primary-hover);
            box-shadow: 0 4px 12px rgba(79, 70, 229, 0.25);
            transform: translateY(-1px);
        }

        button:active {
            transform: translateY(0);
        }

        @media (max-width: 850px) {
            .split-container {
                grid-template-columns: 1fr;
            }
            .image-panel {
                display: none;
            }
            .form-panel {
                padding: 1.5rem;
            }
        }
    </style>
</head>
<body>
    <div class="split-container">
        <!-- Left Side: Image Panel -->
        <div class="image-panel">
            <div class="image-overlay">
                <div class="overlay-text">
                    <h2>Advanced Cardiovascular Diagnostics</h2>
                    <p>Clinical Decision Support powered by explainable AI algorithms.</p>
                </div>
            </div>
        </div>
        
        <!-- Right Side: Form Panel -->
        <div class="form-panel">
            <div class="login-card">
                <div class="login-header">
                    <h1>CVD CDSS</h1>
                    <p>Register Clinician Account</p>
                </div>
                
                {% if error %}
                    <div class="error-message">{{ error }}</div>
                {% endif %}
                {% if success %}
                    <div class="success-message">{{ success }}</div>
                {% endif %}
                
                <form method="POST" onsubmit="return validateForm()">
                    <div class="form-group">
                        <label for="username">Desired Username</label>
                        <input type="text" name="username" id="username" required placeholder="e.g. dr_smith">
                    </div>
                    <div class="form-group">
                        <label for="password">Password (min 6 characters)</label>
                        <input type="password" name="password" id="password" required placeholder="••••••••" minlength="6" oninput="checkMatch()">
                    </div>
                    <div class="form-group">
                        <label for="confirm_password">Confirm Password</label>
                        <input type="password" name="confirm_password" id="confirm_password" required placeholder="••••••••" minlength="6" oninput="checkMatch()">
                        <div id="match-status" style="font-size: 0.8rem; margin-top: 0.35rem; font-weight: 500;"></div>
                    </div>
                    <div style="display: flex; align-items: center; gap: 0.5rem; margin-bottom: 1.25rem; font-size: 0.85rem; color: var(--text-muted); cursor: pointer;">
                        <input type="checkbox" id="show-pass" onchange="togglePasswords(this.checked)" style="width: auto; cursor: pointer;">
                        <label for="show-pass" style="margin: 0; cursor: pointer; font-weight: normal; color: inherit;">Show passwords</label>
                    </div>
                    <button type="submit" id="submit-btn">Create Account</button>
                </form>
                
                <script>
                    function togglePasswords(show) {
                        const p1 = document.getElementById('password');
                        const p2 = document.getElementById('confirm_password');
                        const type = show ? 'text' : 'password';
                        p1.type = type;
                        p2.type = type;
                    }
                    
                    function checkMatch() {
                        const p1 = document.getElementById('password').value;
                        const p2 = document.getElementById('confirm_password').value;
                        const status = document.getElementById('match-status');
                        
                        if (!p2) {
                            status.innerHTML = '';
                            return;
                        }
                        
                        if (p1 === p2) {
                            status.style.color = '#16a34a';
                            status.innerHTML = '✓ Passwords match';
                        } else {
                            status.style.color = '#dc2626';
                            status.innerHTML = '✗ Passwords do not match';
                        }
                    }
                    
                    function validateForm() {
                        const p1 = document.getElementById('password').value;
                        const p2 = document.getElementById('confirm_password').value;
                        if (p1 !== p2) {
                            alert('Passwords do not match! Please check both fields.');
                            return false;
                        }
                        if (p1.length < 6) {
                            alert('Password must be at least 6 characters.');
                            return false;
                        }
                        return true;
                    }
                </script>
                
                <div style="margin-top: 1.5rem; text-align: center; font-size: 0.9rem; color: var(--text-muted);">
                    Already registered? <a href="/login" style="color: var(--primary); font-weight: 600; text-decoration: none;">Log In</a>
                </div>
                
                <div style="margin-top: 2rem; text-align: center; font-size: 0.8rem; color: var(--text-muted);">
                    Secure Registration • HIPAA Audited
                </div>
            </div>
        </div>
    </div>
</body>
</html>
"""


LOGS_TEMPLATE = """
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HIPAA Audit Logs - CVD CDSS</title>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg-color: #f8fafc;
            --card-bg: #ffffff;
            --text-main: #0f172a;
            --text-muted: #64748b;
            --primary: #4f46e5;
            --border-color: #e2e8f0;
        }

        body {
            font-family: 'Outfit', sans-serif;
            background-color: var(--bg-color);
            color: var(--text-main);
            margin: 0;
            padding: 2rem;
        }

        .container {
            max-width: 1000px;
            margin: 0 auto;
        }

        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 2rem;
        }

        .header h1 {
            font-size: 1.75rem;
            font-weight: 700;
            margin: 0;
        }

        .back-link {
            font-size: 0.95rem;
            color: var(--primary);
            text-decoration: none;
            font-weight: 500;
        }

        .card {
            background-color: var(--card-bg);
            border: 1px solid var(--border-color);
            border-radius: 0.75rem;
            padding: 1.5rem;
            box-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1);
        }

        table {
            width: 100%;
            border-collapse: collapse;
            text-align: left;
            font-size: 0.9rem;
        }

        th {
            padding: 0.75rem 1rem;
            border-bottom: 2px solid var(--border-color);
            color: var(--text-muted);
            font-weight: 600;
        }

        td {
            padding: 0.75rem 1rem;
            border-bottom: 1px solid var(--border-color);
        }

        tr:last-child td {
            border-bottom: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>HIPAA Audit Logs</h1>
            <a href="/" class="back-link">← Back to Dashboard</a>
        </div>
        
        <div class="card" style="overflow-x: auto;">
            <table>
                <thead>
                    <tr>
                        <th>Timestamp</th>
                        <th>User</th>
                        <th>IP Address</th>
                        <th>Action</th>
                        <th>Patient ID</th>
                    </tr>
                </thead>
                <tbody>
                    {% for log in logs %}
                        <tr>
                            <td>{{ log.timestamp.strftime("%Y-%m-%d %H:%M:%S") }}</td>
                            <td>{{ log.username }}</td>
                            <td>{{ log.ip_address }}</td>
                            <td><strong style="color: var(--primary);">{{ log.action }}</strong></td>
                            <td style="font-family: monospace;">{{ log.patient_id or 'N/A' }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>
"""


PAGE_TEMPLATE = """
<!doctype html>


<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CVD Risk Screening Tool</title>
    <script src="https://cdn.plot.ly/plotly-2.24.1.min.js" charset="utf-8"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap');

        :root {
            --bg-color: #f1f5f9;
            --text-main: #0f172a;
            --text-muted: #64748b;
            --border-color: #e2e8f0;
            --primary: #4f46e5;
            --primary-hover: #4338ca;
            --primary-light: rgba(79, 70, 229, 0.15);
            --success: #059669;
            --success-light: #ecfdf5;
            --success-border: #a7f3d0;
            --danger: #dc2626;
            --danger-light: #fef2f2;
            --danger-border: #fca5a5;
            --card-bg: #ffffff;
            --font: 'Outfit', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
        }

        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        body {
            font-family: var(--font);
            background-color: var(--bg-color);
            color: var(--text-main);
            line-height: 1.5;
            padding: 2rem 1rem;
        }

        .dashboard-container {
            max-width: 1200px;
            margin: 0 auto;
        }

        .top-nav {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 0.75rem 1.5rem;
            background-color: var(--card-bg);
            border: 1px solid var(--border-color);
            border-radius: 0.75rem;
            margin-bottom: 2rem;
            box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.05);
        }

        .nav-brand {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            font-weight: 700;
            color: var(--text-main);
            font-size: 1.05rem;
        }

        .nav-links a {
            font-size: 0.9rem;
            color: var(--text-muted);
            text-decoration: none;
            font-weight: 500;
            padding: 0.4rem 0.8rem;
            border-radius: 0.375rem;
            transition: all 0.2s ease;
        }

        .nav-links a:hover {
            color: var(--primary);
            background-color: var(--bg-color);
        }

        .nav-links a.active {
            color: var(--primary);
            background-color: var(--primary-light);
            font-weight: 600;
        }

        .dashboard-header {
            margin-bottom: 2rem;
            text-align: center;
        }

        .dashboard-header h1 {
            font-size: 2.25rem;
            font-weight: 700;
            color: var(--text-main);
            background: linear-gradient(135deg, #1e1b4b 0%, #4f46e5 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 0.4rem;
        }

        .dashboard-header p {
            font-size: 0.95rem;
            color: var(--text-muted);
            font-weight: 400;
        }

        .dashboard-grid {
            display: grid;
            grid-template-columns: 1.15fr 0.85fr;
            gap: 2rem;
            align-items: start;
        }

        .card {
            background-color: var(--card-bg);
            border: 1px solid var(--border-color);
            border-radius: 0.75rem;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.02);
            padding: 2rem;
            transition: box-shadow 0.2s ease-in-out;
        }

        .card:hover {
            box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.05), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
        }

        .card-title {
            font-size: 1.2rem;
            font-weight: 600;
            color: var(--text-main);
            margin-bottom: 1.5rem;
            border-bottom: 2px solid #f8fafc;
            padding-bottom: 0.75rem;
        }

        .sub-section-title {
            font-size: 0.95rem;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: var(--text-muted);
            margin-bottom: 1rem;
            margin-top: 1.5rem;
        }

        .form-group {
            margin-bottom: 1.25rem;
        }

        label {
            display: block;
            font-size: 0.875rem;
            font-weight: 500;
            color: var(--text-main);
            margin-bottom: 0.5rem;
        }

        select, input[type=number], input[type=text], input[type=date] {
            width: 100%;
            padding: 0.75rem 1rem;
            font-size: 0.95rem;
            font-family: var(--font);
            color: var(--text-main);
            background-color: var(--card-bg);
            border: 1px solid var(--border-color);
            border-radius: 0.5rem;
            transition: all 0.2s ease-in-out;
        }

        select:focus, input[type=number]:focus, input[type=text]:focus, input[type=date]:focus {
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 3px var(--primary-light);
        }

        .sub-card {
            background-color: #f8fafc;
            border: 1px solid var(--border-color);
            border-radius: 0.5rem;
            padding: 1.25rem;
            margin-bottom: 1.5rem;
        }

        button[type=submit] {
            width: 100%;
            padding: 0.875rem;
            font-size: 1rem;
            font-weight: 600;
            font-family: var(--font);
            color: white;
            background-color: var(--primary);
            border: none;
            border-radius: 0.5rem;
            cursor: pointer;
            transition: all 0.2s ease-in-out;
            margin-top: 1.5rem;
            box-shadow: 0 2px 4px rgba(79, 70, 229, 0.2);
        }

        button[type=submit]:hover {
            background-color: var(--primary-hover);
            box-shadow: 0 4px 12px rgba(79, 70, 229, 0.25);
            transform: translateY(-1px);
        }

        button[type=submit]:active {
            transform: translateY(0);
        }

        .waiting-state {
            text-align: center;
            padding: 4rem 2rem;
            color: var(--text-muted);
        }

        .waiting-state svg {
            margin-bottom: 1rem;
            color: #cbd5e1;
        }

        .waiting-state h3 {
            font-size: 1.125rem;
            font-weight: 600;
            color: var(--text-main);
            margin-bottom: 0.5rem;
        }

        .waiting-state p {
            font-size: 0.9rem;
        }

        .result-card {
            animation: fadeIn 0.4s ease-out;
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
                transform: translateY(10px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        .risk-gauge-container {
            display: flex;
            flex-direction: column;
            align-items: center;
            margin: 1.5rem 0;
        }

        .risk-circle {
            width: 150px;
            height: 150px;
            border-radius: 50%;
            display: flex;
            justify-content: center;
            align-items: center;
            position: relative;
            background: #f1f5f9;
        }

        .result-card.high .risk-circle {
            background: conic-gradient(var(--danger) calc(var(--risk-pct-val) * 1%), #f1f5f9 0);
        }

        .result-card.low .risk-circle {
            background: conic-gradient(var(--success) calc(var(--risk-pct-val) * 1%), #f1f5f9 0);
        }

        .risk-circle-inner {
            width: 122px;
            height: 122px;
            background-color: var(--card-bg);
            border-radius: 50%;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);
        }

        .risk-circle-value {
            font-size: 2rem;
            font-weight: 700;
            line-height: 1;
        }

        .risk-circle-label {
            font-size: 0.7rem;
            text-transform: uppercase;
            font-weight: 600;
            color: var(--text-muted);
            margin-top: 0.25rem;
            letter-spacing: 0.05em;
        }

        .badge {
            display: inline-block;
            padding: 0.375rem 1rem;
            font-size: 0.85rem;
            font-weight: 600;
            border-radius: 9999px;
            margin-bottom: 1rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            text-align: center;
        }

        .result-card.high .risk-circle-value {
            color: var(--danger);
        }

        .result-card.high .badge {
            background-color: var(--danger-light);
            color: var(--danger);
            border: 1px solid var(--danger-border);
        }

        .result-card.low .risk-circle-value {
            color: var(--success);
        }

        .result-card.low .badge {
            background-color: var(--success-light);
            color: var(--success);
            border: 1px solid var(--success-border);
        }

        .risk-description {
            font-size: 0.95rem;
            color: var(--text-muted);
            margin-bottom: 2rem;
            text-align: center;
        }

        .chart-container {
            margin-top: 1.5rem;
            border-top: 1px solid var(--border-color);
            padding-top: 1.5rem;
        }

        .chart-container h4 {
            font-size: 0.95rem;
            font-weight: 600;
            color: var(--text-main);
            margin-bottom: 1rem;
        }

        .chart-container img {
            width: 100%;
            height: auto;
            border-radius: 0.5rem;
            border: 1px solid var(--border-color);
        }

        @media (max-width: 768px) {
            .dashboard-grid {
                grid-template-columns: 1fr;
            }
            body {
                padding: 1.5rem 1rem;
            }
        }

        .visit-row {
            display: flex;
            justify-content: space-between;
            padding: 0.6rem 0;
            border-bottom: 1px dashed var(--border-color);
            font-size: 0.9rem;
        }
        
        .visit-row:last-child {
            border-bottom: none;
        }

        .patient-details-badge {
            font-size: 0.85rem;
            background-color: #f1f5f9;
            color: var(--text-muted);
            padding: 0.25rem 0.75rem;
            border-radius: 0.25rem;
            margin-right: 0.5rem;
            display: inline-block;
            margin-bottom: 0.5rem;
            border: 1px solid var(--border-color);
        }
    </style>
</head>
<body>
    <div class="dashboard-container">
        <div class="top-nav">
            <div class="nav-brand">
                <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" style="margin-right: 0.25rem;">
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"/>
                </svg>
                <span>CVD Risk Assistant</span>
                <span style="font-size: 0.75rem; background-color: var(--primary-light); color: var(--primary); padding: 0.15rem 0.5rem; border-radius: 9999px; font-weight: 600; margin-left: 0.25rem;">v2.1.0-secure</span>
            </div>
            <div style="display: flex; align-items: center; gap: 1.5rem;">
                <span style="font-size: 0.85rem; color: var(--text-muted);">Logged in: <strong style="color: var(--text-main);">{{ current_user.username }}</strong> ({{ current_user.role }})</span>
                <div class="nav-links" style="display: flex; gap: 0.5rem; align-items: center;">
                    {% if current_user.role == 'Administrator' %}
                        <a href="/admin/logs">View Logs</a>
                    {% endif %}
                    <a href="/logout" style="color: var(--danger); background-color: var(--danger-light); padding: 0.4rem 0.8rem; border-radius: 0.375rem; font-size: 0.85rem; font-weight: 600; text-decoration: none;">Logout</a>
                </div>
            </div>
        </div>
        <header class="dashboard-header">
            <h1>Cardiovascular Disease Risk Prediction</h1>
            <p>Optimized clinical screening assistant</p>
        </header>
        
        <div class="dashboard-grid">
            <!-- Left Card: Patient Metrics Form -->
            <div class="card">
                <h2 class="card-title">Patient Metrics</h2>
                <form method="POST">
                    
                    <div class="sub-card">
                        <h3 style="font-size: 0.95rem; font-weight: 600; margin-bottom: 1rem; color: var(--text-main);">Patient Information</h3>
                        
                        <!-- Hidden input for patient_id since dropdown is removed -->
                        <input type="hidden" name="patient_id" id="patient_id" value="">
                        
                        <div class="form-group" style="margin-bottom: 1rem;">
                            <label>Intake Method</label>
                            <div style="display: flex; gap: 1.5rem; margin-top: 0.25rem;">
                                <label style="font-weight: normal; cursor: pointer; display: flex; align-items: center; gap: 0.35rem; font-size: 0.9rem; color: var(--text-main);">
                                    <input type="radio" name="intake_method" value="manual" checked onchange="toggleIntakeMode(this.value)" style="width: auto; margin: 0;"> Register New Patient
                                </label>
                                <label style="font-weight: normal; cursor: pointer; display: flex; align-items: center; gap: 0.35rem; font-size: 0.9rem; color: var(--text-main);">
                                    <input type="radio" name="intake_method" value="fhir" onchange="toggleIntakeMode(this.value)" style="width: auto; margin: 0;"> Fetch from EHR (FHIR)
                                </label>
                            </div>
                        </div>

                        <!-- FHIR Search Field (Initially hidden) -->
                        <div id="fhir_fields_container" style="display: none; margin-bottom: 1rem; border-left: 3px solid var(--primary-light); padding-left: 1rem;">
                            <div class="form-group" style="display: flex; gap: 0.5rem; align-items: flex-end;">
                                <div style="flex: 1;">
                                    <label for="ehr_id">Fetch from EHR (FHIR ID)</label>
                                    <input type="text" id="ehr_id" placeholder="e.g. fhir-1" style="width: 100%; padding: 0.75rem 1rem; border: 1px solid var(--border-color); border-radius: 0.5rem; font-family: inherit; font-size: 0.95rem; color: var(--text-main); box-sizing: border-box;">
                                </div>
                                <button type="button" onclick="fetchEHR()" style="width: auto; padding: 0.75rem 1.25rem; font-size: 0.9rem; background-color: var(--primary); color: white; border: none; border-radius: 0.5rem; cursor: pointer; white-space: nowrap; margin-bottom: 0;">Fetch</button>
                            </div>
                            <div id="fhir_patient_summary" style="display: none; padding: 0.5rem; background-color: var(--success-light); color: var(--success); border: 1px solid var(--success-border); border-radius: 0.375rem; font-size: 0.85rem; margin-top: 0.5rem;"></div>
                        </div>
                        
                        <!-- Manual Entry Fields (Initially visible) -->
                        <div id="new_patient_fields" style="border-left: 3px solid var(--primary-light); padding-left: 1rem; margin-top: 1rem;">
                            <div class="form-group">
                                <label for="patient_name">Patient Name</label>
                                <input type="text" name="patient_name" id="patient_name" placeholder="John Doe">
                            </div>
                            <div class="form-group">
                                <label for="patient_dob">Date of Birth</label>
                                <input type="date" name="patient_dob" id="patient_dob">
                            </div>
                            <div class="form-group">
                                <label for="patient_gender">Gender</label>
                                <select name="patient_gender" id="patient_gender">
                                    <option value="Male">Male</option>
                                    <option value="Female">Female</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="patient_fhir_id">Patient EHR FHIR ID (Optional)</label>
                                <input type="text" name="patient_fhir_id" id="patient_fhir_id" placeholder="e.g. fhir-1">
                            </div>
                        </div>
                    </div>
                    
                    <h3 class="sub-section-title">Clinical Metrics</h3>
                    
                    {% for field in fields %}
                        {% if field.type == 'select' %}
                            <div class="form-group">
                                <label for="{{ field.key }}">{{ field.label }}</label>
                                <select name="{{ field.key }}" id="{{ field.key }}">
                                    {% for opt_name, opt_val in field.options %}
                                        <option value="{{ opt_val }}">{{ opt_name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        {% elif field.type == 'st_slope' %}
                            <div class="form-group">
                                <label for="ST_Slope">ST Slope (ECG)</label>
                                <select name="ST_Slope" id="ST_Slope">
                                    <option value="Up">Up</option>
                                    <option value="Flat">Flat</option>
                                    <option value="Down">Down</option>
                                </select>
                            </div>
                        {% elif field.type == 'chest_pain' %}
                            <div class="form-group">
                                <label for="ChestPainType">Chest Pain Type</label>
                                <select name="ChestPainType" id="ChestPainType">
                                    <option value="ATA">Atypical Angina (ATA)</option>
                                    <option value="NAP">Non-Anginal Pain (NAP)</option>
                                    <option value="ASY">Asymptomatic (ASY)</option>
                                    <option value="TA">Typical Angina (TA)</option>
                                </select>
                            </div>
                        {% else %}
                            <div class="form-group">
                                <label for="{{ field.key }}">{{ field.label }}</label>
                                <input type="number" step="0.01" name="{{ field.key }}" id="{{ field.key }}" value="0">
                            </div>
                        {% endif %}
                    {% endfor %}
                    <button type="submit">Get Risk Score</button>
                </form>
            </div>
            
            <!-- Right Card: Diagnostic Result & Trajectory -->
            <div class="card" style="min-height: 400px; display: flex; flex-direction: column; gap: 2rem;">
                
                <!-- Prediction Result -->
                <div>
                    {% if result %}
                        <div class="result-card {{ 'high' if result.risk_pct >= 50 else 'low' }}">
                            <h2 class="card-title">Analysis Result</h2>
                            
                            <div class="risk-gauge-container" style="--risk-pct-val: {{ result.risk_pct }}">
                                <div class="risk-circle">
                                    <div class="risk-circle-inner">
                                        <div class="risk-circle-value">{{ result.risk_pct }}%</div>
                                        <div class="risk-circle-label">CVD Risk</div>
                                    </div>
                                </div>
                            </div>
                            
                            <div style="text-align: center; margin-bottom: 1rem;">
                                <span class="badge">{{ 'High Risk' if result.risk_pct >= 50 else 'Low Risk' }}</span>
                            </div>
                            
                            <p class="risk-description">
                                {{ 'High risk of Cardiovascular Disease. Further clinical evaluation and diagnostic testing are recommended.' if result.risk_pct >= 50 else 'Low risk of Cardiovascular Disease based on current key clinical indicators.' }}
                            </p>
                            <div class="chart-container">
                                <h4>Feature Contributions (SHAP explanation)</h4>
                                <div id="shap-chart" style="width: 100%; min-height: 230px;"></div>
                            </div>
                            
                            {% if result.recommendations %}
                                <div style="margin-top: 1.5rem; border-top: 1px solid var(--border-color); padding-top: 1.5rem;">
                                    <h4 style="font-size: 0.95rem; font-weight: 600; color: var(--text-main); margin-bottom: 0.75rem;">Clinical Recommendations</h4>
                                    <ul style="padding-left: 1.25rem; font-size: 0.9rem; color: var(--text-muted); display: flex; flex-direction: column; gap: 0.5rem; text-align: left;">
                                        {% for rec in result.recommendations %}
                                            <li>{{ rec }}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endif %}
                            
                            {% if result.visit_id %}
                                <div style="margin-top: 1.5rem; text-align: center;">
                                    <a href="/visit/{{ result.visit_id }}/pdf" style="display: inline-flex; align-items: center; justify-content: center; gap: 0.5rem; text-decoration: none; padding: 0.6rem 1.25rem; border-radius: 0.5rem; background-color: var(--primary); color: white; font-weight: 600; font-size: 0.9rem; transition: background-color 0.2s;" onmouseover="this.style.backgroundColor='var(--primary-hover)'" onmouseout="this.style.backgroundColor='var(--primary)'">
                                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" style="margin-right: 0.25rem;">
                                            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                                            <polyline points="7 10 12 15 17 10"/>
                                            <line x1="12" y1="15" x2="12" y2="3"/>
                                        </svg>
                                        Download Diagnostic Report (PDF)
                                    </a>
                                </div>
                            {% endif %}
                        </div>
                    {% else %}
                        <div class="waiting-state" style="margin: auto;">
                            <svg width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
                                <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/>
                                <path d="M3.22 12H9.5l1.5-3.5L13 16l1.5-5.5 1.5 3.5h3.28"/>
                            </svg>
                            <h3>Awaiting Input</h3>
                            <p>Fill in the patient clinical features on the left and submit to view the predicted risk score and details.</p>
                        </div>
                    {% endif %}
                </div>
                <!-- Patient History & Trajectory -->
                {% if selected_patient %}
                    <div style="border-top: 1px solid var(--border-color); padding-top: 1.5rem; margin-top: 1.5rem;">
                        <h2 class="card-title" style="margin-bottom: 1rem;">Patient History</h2>
                        <div style="margin-bottom: 1.5rem;">
                            <span class="patient-details-badge">Name: {{ selected_patient.name }}</span>
                            <span class="patient-details-badge">DOB: {{ selected_patient.dob }}</span>
                            <span class="patient-details-badge">Gender: {{ selected_patient.gender }}</span>
                            {% if selected_patient.fhir_id %}
                                <span class="patient-details-badge" style="background-color: var(--primary-light); color: var(--primary); font-weight: 600;">FHIR ID: {{ selected_patient.fhir_id }}</span>
                            {% endif %}
                        </div>
                        
                        {% if trajectory_chart %}
                            <div class="chart-container" style="border-top: none; padding-top: 0; margin-bottom: 1.5rem;">
                                <h4>Risk Progression Trajectory</h4>
                                <img src="data:image/png;base64,{{ trajectory_chart }}" alt="Patient risk progression chart">
                            </div>
                        {% endif %}
                        
                        <div>
                            <h4>Previous Visits</h4>
                            <div style="margin-top: 0.5rem; max-height: 200px; overflow-y: auto;">
                                {% for v in previous_visits %}
                                    <div class="visit-row">
                                        <span style="color: var(--text-muted);">{{ v.visit_date.strftime("%Y-%m-%d %H:%M") }}</span>
                                        <span style="font-weight: 600; color: {{ 'var(--danger)' if v.is_high_risk else 'var(--success)' }}">{{ v.predicted_risk }}%</span>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <script>
        function toggleIntakeMode(mode) {
            const manualContainer = document.getElementById("new_patient_fields");
            const fhirContainer = document.getElementById("fhir_fields_container");
            if (mode === "manual") {
                manualContainer.style.display = "block";
                fhirContainer.style.display = "none";
                // Reset hidden fields
                document.getElementById("patient_name").value = "";
                document.getElementById("patient_dob").value = "";
                document.getElementById("patient_gender").value = "Male";
                document.getElementById("patient_fhir_id").value = "";
            } else {
                manualContainer.style.display = "none";
                fhirContainer.style.display = "block";
                // Reset summary
                document.getElementById("fhir_patient_summary").style.display = "none";
                document.getElementById("fhir_patient_summary").innerHTML = "";
            }
        }

        function loadPatient(patientId) {
            var fields = document.getElementById("new_patient_fields");
            if (patientId) {
                fields.style.display = "none";
                window.location.href = "/?patient_id=" + patientId;
            } else {
                fields.style.display = "block";
                window.location.href = "/";
            }
        }

        async function fetchEHR() {
            const ehrId = document.getElementById("ehr_id").value;
            if (!ehrId) {
                alert("Please enter a FHIR Patient ID.");
                return;
            }
            try {
                const response = await fetch(`/api/fhir/Patient/${ehrId}`);
                if (!response.ok) {
                    throw new Error("Patient not found in EHR database.");
                }
                const data = await response.json();
                
                // Show new patient fields if currently hidden
                document.getElementById("patient_id").value = "";
                
                // Fill in patient details
                const patientName = data.name[0].given.join(" ") + " " + data.name[0].family;
                document.getElementById("patient_name").value = patientName;
                document.getElementById("patient_dob").value = data.birthDate;
                document.getElementById("patient_fhir_id").value = ehrId; // Populate FHIR ID field
                
                // Gender mapping
                const gender = data.gender.charAt(0).toUpperCase() + data.gender.slice(1);
                document.getElementById("patient_gender").value = gender;
                
                // Show summary badge since details are hidden
                const summaryEl = document.getElementById("fhir_patient_summary");
                summaryEl.innerHTML = `<strong>Active EHR Record:</strong> ${patientName} (DOB: ${data.birthDate}, ${gender})`;
                summaryEl.style.display = "block";
                
                // Fill in clinical metrics if elements exist
                if (data.clinicalObservations) {
                    const obs = data.clinicalObservations;
                    const possibleFields = ["Sex_M", "ExerciseAngina_Y", "ST_Slope", "ChestPainType", "Oldpeak"];
                    possibleFields.forEach(field => {
                        const el = document.getElementById(field);
                        if (el && obs[field] !== undefined) {
                            el.value = obs[field];
                        }
                    });
                }
                
                alert(`Successfully fetched and populated patient: ${patientName} from EHR!`);
            } catch (err) {
                alert(err.message);
            }
        }

        async function renderShapChart(visitId) {
            try {
                const response = await fetch(`/api/shap/${visitId}`);
                if (!response.ok) throw new Error("Could not fetch SHAP data");
                const data = await response.json();
                
                const sortedFeatures = [...data.features].sort((a, b) => Math.abs(a.value) - Math.abs(b.value));
                
                const yNames = sortedFeatures.map(f => f.name);
                const xValues = sortedFeatures.map(f => f.value);
                const colors = sortedFeatures.map(f => f.value > 0 ? "#ef4444" : "#10b981");
                
                const trace = {
                    type: 'bar',
                    x: xValues,
                    y: yNames,
                    orientation: 'h',
                    marker: {
                        color: colors,
                        width: 0.55
                    },
                    hoverinfo: 'x+y'
                };
                
                const layout = {
                    paper_bgcolor: 'rgba(0,0,0,0)',
                    plot_bgcolor: 'rgba(0,0,0,0)',
                    margin: { l: 140, r: 20, t: 10, b: 45 },
                    xaxis: {
                        title: 'Contribution to Risk (SHAP Value)',
                        zerolineColor: '#cbd5e1',
                        gridcolor: '#e2e8f0',
                        titlefont: { size: 10, color: '#475569' },
                        tickfont: { size: 9, color: '#475569' }
                    },
                    yaxis: {
                        tickfont: { size: 9, color: '#475569' }
                    },
                    height: 220,
                    autosize: true
                };
                
                Plotly.newPlot('shap-chart', [trace], layout, {displayModeBar: false});
            } catch (err) {
                console.error(err);
            }
        }

        {% if result and result.visit_id %}
            renderShapChart({{ result.visit_id }});
        {% endif %}
    </script>
</body>
</html>
"""


@app.route("/", methods=["GET", "POST"])
@login_required
def index():
    result = None
    selected_patient_id = request.args.get("patient_id") or request.form.get("patient_id")
    
    # Ignore URL patient_id if manually registering a new patient
    if request.method == "POST" and request.form.get("intake_method") == "manual":
        selected_patient_id = None
        
    selected_patient = None
    trajectory_chart = None
    previous_visits = []
    
    if selected_patient_id:
        selected_patient = db.session.get(Patient, selected_patient_id)
        if selected_patient:
            previous_visits = selected_patient.visits
            if len(previous_visits) >= 2:
                trajectory_chart = make_trajectory_chart(previous_visits)
            # Log view action
            log_audit("VIEW_PATIENT", patient_id=selected_patient.id)
                
    if request.method == "POST":
        X = encode_input(request.form)

        proba = model.predict_proba(X)[0, 1]
        risk_pct = round(float(proba) * 100, 1)

        # Get or create Patient
        fhir_id = request.form.get("patient_fhir_id")
        if fhir_id == "":
            fhir_id = None
            
        patient = None
        # Check if patient with this FHIR ID already exists to avoid duplication / constraint errors
        if fhir_id:
            patient = Patient.query.filter_by(fhir_id=fhir_id).first()
            
        if not patient and selected_patient_id:
            patient = db.session.get(Patient, selected_patient_id)
            # Update fhir_id if provided and different
            if fhir_id and patient.fhir_id != fhir_id:
                patient.fhir_id = fhir_id
                db.session.commit()
                
        if not patient:
            name = request.form.get("patient_name")
            dob = request.form.get("patient_dob")
            gender = request.form.get("patient_gender")
            if not name or not dob or not gender:
                name = name or "Unknown Patient"
                dob = dob or "1970-01-01"
                gender = gender or "Male"
            patient = Patient(name=name, dob=dob, gender=gender, fhir_id=fhir_id)
            db.session.add(patient)
            db.session.commit()
            # Log registration action
            log_audit("REGISTER_PATIENT", patient_id=patient.id)
            
        # Create and save Visit
        visit = Visit(
            patient_id=patient.id,
            sex=request.form.get("Sex_M", "0"),
            exercise_angina=request.form.get("ExerciseAngina_Y", "0"),
            st_slope=request.form.get("ST_Slope", "Up"),
            chest_pain=request.form.get("ChestPainType", "ATA"),
            oldpeak=float(request.form.get("Oldpeak", 0)),
            predicted_risk=risk_pct,
            is_high_risk=bool(risk_pct >= 50)
        )
        db.session.add(visit)
        db.session.commit()
        
        # Log prediction action
        log_audit("RUN_RISK_PREDICTION", patient_id=patient.id)
        
        # Redirect to the patient's view so they can see the updated trajectory!
        return redirect(url_for("index", patient_id=patient.id, last_visit_id=visit.id))

    # If redirection had last prediction results
    last_visit_id = request.args.get("last_visit_id")
    if last_visit_id:
        v = db.session.get(Visit, last_visit_id)
        if v:
            visit_dict = {
                "Sex_M": v.sex,
                "ExerciseAngina_Y": v.exercise_angina,
                "ST_Slope": v.st_slope,
                "ChestPainType": v.chest_pain,
                "Oldpeak": str(v.oldpeak)
            }
            X_last = encode_input(visit_dict)
            shap_values = explainer.shap_values(X_last)
            shap_row = shap_values[0]
            base_value = explainer.expected_value
            chart_b64 = make_shap_chart(X_last.iloc[0].values, shap_row, base_value)
            
            recs = get_clinical_recommendations(v.predicted_risk, visit_dict)
            
            result = {
                "risk_pct": v.predicted_risk,
                "chart": chart_b64,
                "recommendations": recs,
                "visit_id": v.id
            }

    patients = Patient.query.order_by(Patient.name).all()
    
    return render_template_string(
        PAGE_TEMPLATE, 
        fields=FORM_FIELDS, 
        result=result, 
        patients=patients,
        selected_patient=selected_patient,
        trajectory_chart=trajectory_chart,
        previous_visits=previous_visits
    )


@app.route("/login", methods=["GET", "POST"])
def login():
    error = None
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")
        user = User.query.filter_by(username=username).first()
        if user and user.check_password(password):
            login_user(user)
            log_audit("USER_LOGIN")
            return redirect(url_for("index"))
        else:
            error = "Invalid username or password"
            
    return render_template_string(LOGIN_TEMPLATE, error=error)


@app.route("/register", methods=["GET", "POST"])
def register():
    error = None
    success = None
    if request.method == "POST":
        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")
        confirm_password = request.form.get("confirm_password", "")
        
        if not username or not password or not confirm_password:
            error = "All fields are required"
        elif password != confirm_password:
            error = "Passwords do not match"
        elif len(password) < 6:
            error = "Password must be at least 6 characters long"
        else:
            existing_user = User.query.filter_by(username=username).first()
            if existing_user:
                error = "Username already exists"
            else:
                new_user = User(username=username, role="Clinician")
                new_user.set_password(password)
                db.session.add(new_user)
                db.session.commit()
                # Log registry action
                log_audit(f"REGISTER_USER: {username}")
                return redirect(url_for("login"))
                
    return render_template_string(REGISTER_TEMPLATE, error=error, success=success)


@app.route("/logout")
@login_required
def logout():
    log_audit("USER_LOGOUT")
    logout_user()
    return redirect(url_for("login"))


MOCK_FHIR_PATIENTS = {
    "fhir-1": {
        "resourceType": "Patient",
        "id": "fhir-1",
        "name": [{"family": "Davis", "given": ["Robert"]}],
        "gender": "male",
        "birthDate": "1968-04-12",
        "clinicalObservations": {
            "Sex_M": "1",
            "ExerciseAngina_Y": "1",
            "ST_Slope": "Flat",
            "ChestPainType": "ASY",
            "Oldpeak": "1.5"
        }
    },
    "fhir-2": {
        "resourceType": "Patient",
        "id": "fhir-2",
        "name": [{"family": "Smith", "given": ["Alice"]}],
        "gender": "female",
        "birthDate": "1983-09-22",
        "clinicalObservations": {
            "Sex_M": "0",
            "ExerciseAngina_Y": "0",
            "ST_Slope": "Up",
            "ChestPainType": "ATA",
            "Oldpeak": "0.0"
        }
    },
    "fhir-3": {
        "resourceType": "Patient",
        "id": "fhir-3",
        "name": [{"family": "Miller", "given": ["Charles"]}],
        "gender": "male",
        "birthDate": "1955-11-23",
        "clinicalObservations": {
            "Sex_M": "1",
            "ExerciseAngina_Y": "1",
            "ST_Slope": "Flat",
            "ChestPainType": "TA",
            "Oldpeak": "2.4"
        }
    }
}


@app.route("/api/fhir/Patient/<patient_id>")
@login_required
def get_fhir_patient(patient_id):
    # Log audit access
    log_audit("FHIR_EHR_FETCH_PATIENT", patient_id=patient_id)
    
    patient_data = MOCK_FHIR_PATIENTS.get(patient_id)
    if not patient_data:
        # Fallback: Query local SQLite database for a patient with this fhir_id
        local_patient = Patient.query.filter_by(fhir_id=patient_id).first()
        if local_patient:
            # Get latest visit metrics if available to pre-fill the form
            latest_visit = Visit.query.filter_by(patient_id=local_patient.id).order_by(Visit.visit_date.desc()).first()
            obs = {}
            if latest_visit:
                obs = {
                    "Sex_M": latest_visit.sex,
                    "ExerciseAngina_Y": latest_visit.exercise_angina,
                    "ST_Slope": latest_visit.st_slope,
                    "ChestPainType": latest_visit.chest_pain,
                    "Oldpeak": str(latest_visit.oldpeak)
                }
            patient_data = {
                "resourceType": "Patient",
                "id": local_patient.fhir_id,
                "name": [{"family": local_patient.name.split()[-1] if len(local_patient.name.split()) > 1 else "", 
                          "given": local_patient.name.split()[:-1] if len(local_patient.name.split()) > 1 else [local_patient.name]}],
                "gender": local_patient.gender.lower(),
                "birthDate": local_patient.dob,
                "clinicalObservations": obs
            }
        else:
            return jsonify({"error": "Patient not found in EHR or local database"}), 404
        
    return jsonify(patient_data)


@app.route("/api/shap/<int:visit_id>")
@login_required
def get_shap_json(visit_id):
    visit = db.session.get(Visit, visit_id)
    if not visit:
        return jsonify({"error": "Visit not found"}), 404
        
    visit_dict = {
        "Sex_M": visit.sex,
        "ExerciseAngina_Y": visit.exercise_angina,
        "ST_Slope": visit.st_slope,
        "ChestPainType": visit.chest_pain,
        "Oldpeak": str(visit.oldpeak)
    }
    X = encode_input(visit_dict)
    shap_values = explainer.shap_values(X)
    shap_row = shap_values[0]
    base_value = float(explainer.expected_value)
    
    groups = {
        "Sex": [],
        "Exercise-induced Angina": [],
        "ST Slope": [],
        "Chest Pain Type": [],
        "Oldpeak (ST Depression)": []
    }
    
    for i, feat in enumerate(top5_features):
        val = float(shap_row[i])
        if feat.startswith("Sex"):
            groups["Sex"].append(val)
        elif feat.startswith("ExerciseAngina"):
            groups["Exercise-induced Angina"].append(val)
        elif feat.startswith("ST_Slope"):
            groups["ST Slope"].append(val)
        elif feat.startswith("ChestPainType"):
            groups["Chest Pain Type"].append(val)
        elif feat.startswith("Oldpeak"):
            groups["Oldpeak (ST Depression)"].append(val)
        else:
            clean_name = feat.replace("_", " ")
            if clean_name not in groups:
                groups[clean_name] = []
            groups[clean_name].append(val)
            
    feature_list = []
    for group_name, vals in groups.items():
        if len(vals) > 0:
            feature_list.append({
                "name": group_name,
                "value": round(sum(vals), 4)
            })
            
    return jsonify({
        "base_value": base_value,
        "prediction_probability": visit.predicted_risk / 100.0,
        "features": feature_list
    })


@app.route("/admin/logs")
@login_required
def admin_logs():
    if current_user.role != "Administrator":
        log_audit("UNAUTHORIZED_LOGS_ACCESS_ATTEMPT")
        return "Access Denied: Administrator role required.", 403
        
    log_audit("VIEW_AUDIT_LOGS")
    logs = AuditLog.query.order_by(AuditLog.timestamp.desc()).all()
    return render_template_string(LOGS_TEMPLATE, logs=logs)


@app.route("/visit/<int:visit_id>/pdf")
@login_required
def export_pdf(visit_id):
    import io
    visit = db.get_or_404(Visit, visit_id)
    patient = visit.patient
    
    # Audit log access
    log_audit("EXPORT_PATIENT_REPORT_PDF", patient_id=patient.id)
    
    visit_dict = {
        "Sex_M": visit.sex,
        "ExerciseAngina_Y": visit.exercise_angina,
        "ST_Slope": visit.st_slope,
        "ChestPainType": visit.chest_pain,
        "Oldpeak": str(visit.oldpeak)
    }
    X = encode_input(visit_dict)
    shap_values = explainer.shap_values(X)
    shap_row = shap_values[0]
    base_value = explainer.expected_value
    chart_b64 = make_shap_chart(X.iloc[0].values, shap_row, base_value)
    
    # Generate recommendations
    recs = get_clinical_recommendations(visit.predicted_risk, visit_dict)
    
    # Generate PDF in memory
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40
    )
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#0f172a'),
        spaceAfter=15
    )
    section_style = ParagraphStyle(
        'DocSection',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=13,
        leading=16,
        textColor=colors.HexColor('#4f46e5'),
        spaceBefore=15,
        spaceAfter=10
    )
    body_style = ParagraphStyle(
        'DocBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#334155')
    )
    body_bold = ParagraphStyle(
        'DocBodyBold',
        parent=body_style,
        fontName='Helvetica-Bold'
    )
    
    elements = []
    
    # Header Title
    elements.append(Paragraph("Cardiovascular Disease Diagnostic Report", title_style))
    elements.append(Paragraph(f"Generated on: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}", body_style))
    elements.append(Spacer(1, 15))
    
    # Patient info
    data = [
        [Paragraph("<b>Patient Name:</b>", body_style), Paragraph(patient.name, body_style),
         Paragraph("<b>Date of Birth:</b>", body_style), Paragraph(patient.dob, body_style)],
        [Paragraph("<b>Gender:</b>", body_style), Paragraph(patient.gender, body_style),
         Paragraph("<b>EHR FHIR ID:</b>", body_style), Paragraph(patient.fhir_id or "Not Linked", body_style)],
        [Paragraph("<b>Record UUID:</b>", body_style), Paragraph(patient.id, body_style),
         Paragraph("", body_style), Paragraph("", body_style)]
    ]
    t = Table(data, colWidths=[110, 150, 100, 160])
    t.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#f8fafc')),
        ('BACKGROUND', (2,0), (2,-1), colors.HexColor('#f8fafc')),
        ('PADDING', (0,0), (-1,-1), 6),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 15))
    
    # Metrics
    elements.append(Paragraph("Screening Metrics & Result", section_style))
    metrics_data = [
        [Paragraph("<b>Clinical Metric</b>", body_bold), Paragraph("<b>Value Entered</b>", body_bold)],
        [Paragraph("Chest Pain Type", body_style), Paragraph(visit.chest_pain, body_style)],
        [Paragraph("Sex", body_style), Paragraph("Male" if visit.sex == "1" else "Female", body_style)],
        [Paragraph("Exercise-Induced Angina", body_style), Paragraph("Yes" if visit.exercise_angina == "1" else "No", body_style)],
        [Paragraph("ST Slope (ECG)", body_style), Paragraph(visit.st_slope, body_style)],
        [Paragraph("Oldpeak (ST Depression)", body_style), Paragraph(f"{visit.oldpeak} mm", body_style)]
    ]
    t_metrics = Table(metrics_data, colWidths=[200, 320])
    t_metrics.setStyle(TableStyle([
        ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#f1f5f9')),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    elements.append(t_metrics)
    elements.append(Spacer(1, 15))
    
    # Risk Summary
    risk_color = '#ef4444' if visit.predicted_risk >= 50 else '#10b981'
    risk_text = f"<b>Predicted CVD Risk: <font color='{risk_color}'>{visit.predicted_risk}%</font></b> ({'HIGH RISK' if visit.predicted_risk >= 50 else 'LOW RISK'})"
    elements.append(Paragraph(risk_text, ParagraphStyle('RiskText', parent=body_style, fontSize=12, leading=16)))
    elements.append(Spacer(1, 15))
    
    # Recommendations
    elements.append(Paragraph("Clinical Recommendations", section_style))
    for rec in recs:
        elements.append(Paragraph(f"• {rec}", body_style))
        elements.append(Spacer(1, 4))
    elements.append(Spacer(1, 15))
    
    # Embed SHAP chart
    elements.append(Paragraph("Feature Attributions (Explainable AI / SHAP)", section_style))
    chart_data = base64.b64decode(chart_b64)
    chart_io = io.BytesIO(chart_data)
    img = Image(chart_io, width=320, height=117)
    elements.append(img)
    
    # Page 2: Patient Education Guide
    elements.append(PageBreak())
    elements.append(Paragraph("Patient Education Guide: Understanding Your Condition", title_style))
    elements.append(Paragraph("This educational section is designed to help you understand your symptoms, clinical findings, and risk factors in simple terms. Always consult your physician for personalized medical advice.", body_style))
    elements.append(Spacer(1, 12))
    
    # Specific patient symptom education
    cp_code = visit.chest_pain
    cp_info = CHEST_PAIN_EDUCATION.get(cp_code, CHEST_PAIN_EDUCATION["ASY"])
    
    elements.append(Paragraph(f"Your Symptom Classification: {cp_info['name']}", section_style))
    elements.append(Paragraph(f"<b>What is it?</b><br/>{cp_info['description']}", body_style))
    elements.append(Spacer(1, 8))
    elements.append(Paragraph(f"<b>Typical Clinical Causes:</b><br/>{cp_info['causes']}", body_style))
    elements.append(Spacer(1, 8))
    elements.append(Paragraph(f"<b>How to manage & overcome:</b><br/>{cp_info['overcome']}", body_style))
    elements.append(Spacer(1, 15))
    
    # Reference guide table for all chest pain types
    elements.append(Paragraph("Reference Guide: Chest Pain Types & Causes", section_style))
    ref_data = [
        [Paragraph("<b>Classification</b>", body_bold), Paragraph("<b>Clinical Meaning & Common Causes</b>", body_bold)]
    ]
    for code, info in CHEST_PAIN_EDUCATION.items():
        ref_data.append([
            Paragraph(f"<b>{info['name']} ({code})</b>", body_bold),
            Paragraph(f"<i>What is it:</i> {info['description']}<br/><i>Common Causes:</i> {info['causes']}<br/><i>Management:</i> {info['overcome']}", body_style)
        ])
    t_ref = Table(ref_data, colWidths=[130, 390])
    t_ref.setStyle(TableStyle([
        ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#f8fafc')),
        ('PADDING', (0,0), (-1,-1), 6),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
    ]))
    elements.append(t_ref)
    
    # Build
    doc.build(elements)
    buffer.seek(0)
    
    return send_file(
        buffer,
        as_attachment=True,
        download_name=f"cvd_report_{patient.name.replace(' ', '_')}_{visit_id}.pdf",
        mimetype="application/pdf"
    )


if __name__ == "__main__":
    print(f"Model expects features: {top5_features}")
    print(f"Decision threshold used: {threshold}")
    app.run(debug=True)